default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gift_list_api_development
  username: joshseckman
  password: Michigan1
  host: localhost
  port: 5432

test:
  <<: *default
  database: gift_list_api_test

production:
  <<: *default
  url: <%= ENV['DATBASE_URL'] %>
